apiVersion: v1
kind: Service
metadata: 
  name: web-app
  labels:
    app: web-app
spec:
  selector:
      app: web-app
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP